name: Build and Push Docker Images

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push-java-api:
    name: Java API - Build and Push
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/java-api:latest .

    - name: Push to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/java-api:latest

  build-and-push-chatbot:
    name: Chatbot - Build and Push
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: machine_learning/chatbot

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build \
          --build-arg HUGGINGFACEHUB_API_TOKEN=${{ secrets.HUGGINGFACEHUB_API_TOKEN }} \
          -t ${{ secrets.DOCKER_USERNAME }}/chatbot:latest .

    - name: Run container for test
      run: |
        docker run -e HUGGINGFACEHUB_API_TOKEN=${{ secrets.HUGGINGFACEHUB_API_TOKEN }} \
                   ${{ secrets.DOCKER_USERNAME }}/chatbot:latest



    - name: Push to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/chatbot:latest

  build-and-push-loan-ml:
    name: Loan ML - Build and Push
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: machine_learning/loan_approve_ml_model

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/loan-approve-ml:latest .

    - name: Push to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/loan-approve-ml:latest
